export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const LOADING = "LOADING";